#ifndef PLUGIN_EXCEPTS_H
#define PLUGIN_EXCEPTS_H

#ifdef __cplusplus
extern "C" {
#endif
enum GNFPLUGIN_ERROR_CODE
{
	GNFPLUGIN_ERROR_CODE_VERSION_NOT_COMPATIBLE = 1,
	GNFPLUGIN_ERROR_CODE_PLUGIN_NAME_EXIST,
	GNFPLUGIN_ERROR_CODE_OPEN_PACKAGED_TYPE_NOT_COMPATIBLE_BIND_TYPE,
	GNFPLUGIN_ERROR_CODE_CONFIGPROP_NAME_INVALID
};
#ifdef __cplusplus
}
#endif
#endif
