#pragma once
#define _SILENCE_ALL_CXX23_DEPRECATION_WARNINGS
#include <taskflow/taskflow.hpp>
#include <unknwn.h>
#include <windows.h>
#undef min
#undef max
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.ApplicationModel.Core.h>
#include <winrt/Windows.UI.Core.h>
#include <winrt/Windows.UI.Composition.h>
#include <winrt/Windows.UI.Input.h>

#include "directx_wrapper.h"
#include "Common/Logger.h"
#include "Common/Utils/utils_win32.h"
#include <glm/glm.hpp>
#include "imgui/imgui.h"
